# Generated by Django 4.0.5 on 2022-07-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r2sus', '0002_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='score',
            field=models.CharField(max_length=20),
        ),
    ]
