# Generated by Django 4.0.5 on 2022-07-01 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('r2sus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=7)),
                ('username', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
