export { default as Home } from './Home'
export { default as Class } from './Class'
export { default as About } from './About'
export { default as Activity } from './Activity'
export { default as Marketplace } from './MarketPlace'
export { default as Profile } from './Profile'
